spring:
  profiles:
    dev

  datasource:
    url: $(DB_URL:jdbc:postgresql://db:5432/orchestrator)
    username: $(DB_USERNAME:postgres)
    password: $(DB_PASSWORD:secret)
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      show-sql: true

logging:
  level:
    root: INFO
    com.example.orchestrator: DEBUG
    com.hibernate.SQL: TRACE
    com.springframework: WARN