server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: orchestrator

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  jwt:
    secret: "s47f9gJtzw9uJYrWn4OMV9ys9cIn7eF0WSGw4z7mBXo="
    expiration-ms: 24